### ISSUE TITLE
Unable to add new parts to existing package

### ISSUE THREAD

**Issue by aelray** [qmuntal/opc#17]
Hi,

I have a problem reopening an existing file and adding further parts to it.

I reopen the file with the following:
```
p.reader, err = opc.OpenReader(outputFilePath)
p.writer, err = opc.NewWriterFromReader(&bytes.Buffer{}, p.reader.Reader)
```
and I get no error. In the debugger I can also see that the correct file is opened with files added previously.

However, when I attach new files using:
```
name := opc.NormalizePartName(contentType.PackagePath + "/" + fileName)
part, err := p.writer.Create(name, contentType.Value)
bytes, err := ioutil.ReadFile(contentFilePath)
// Write content to the part.
part.Write(bytes)
```
I see in the debugger that everything is added to the object but nothing is finally added to the file.

I also tried 
```
part, err := p.writer.CreatePart(&opc.Part{
        Name:        name,
	ContentType: contentType.Value,
}, opc.CompressionNormal)
```
instead of 
```
part, _ := p.writer.Create(name, contentType.Value)
```
but it has the same effect.

What am I doing wrong or is there a bug?

**Comment by qmuntal** [comment]
`NewWriterFromReader` does not modify the original file, it just make a copy of all the parts (without decompressing) and writes them in `w` (the first parameter of the function). At the end it is just helper function, no dark magic inside which can safe from copying the content, although it will possibly improve if https://github.com/golang/go/issues/34974 is finally implemented.

I guess that you problem is that you are calling `NewWriterFromReader` with `&bytes.Buffer{}` and that this buffer is never written into a file. If you confirm that this is the problem I´ll update the method docs to remark that the origin file is not modified.

**Comment by aelray** [comment]
Thank you for your response, how do I write the buffer?

**Comment by qmuntal** [comment]
Check the example of this function: https://pkg.go.dev/github.com/qmuntal/opc#example-NewWriterFromReader.

Once you are done writing to the new package you can do whatever with the buffer, even replacing the original file with the new content:

```go
r, _ := opc.OpenReader(outputFilePath)

// do whatever read operation on r...

buf := new(bytes.Buffer)
w, _ := opc.NewWriterFromReader(buf, r.Reader)
r.Close() // Close the original file so it can be overwitted

// do whatever write operation on w...

w.Close()
ioutil.WriteFile(outputFilePath, buf.Bytes(), 0644) // overwrite the original file
```

**Comment by aelray** [comment]
That did it, thank you!
