### ISSUE TITLE
Missing Dublin Core complex type in the Core Properties XML

### ISSUE THREAD

**Issue by juandemanjon** [qmuntal/opc#8]
According to [Notes on the W3C XML Schemas for Qualified Dublin Core](https://dublincore.org/schemas/xmls/qdc/2008/02/11/notes/), the Core properties dates should be serialized with _xsi:type="dcterms:W3CDTF"_ like **_dcterms:created_** and **_dcterms:modified_** in the below example:

```
<?xml version="1.0" encoding="UTF-8"?>
<coreProperties xmlns="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:dcterms="http://purl.org/dc/terms/"
    xmlns:dcmitype="http://purl.org/dc/dcmitype/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <dcterms:created xsi:type="dcterms:W3CDTF">2020-10-15T04:05:00Z</dcterms:created>
    <dc:creator>Microsoft Office User</dc:creator>
    <lastModifiedBy>Microsoft Office User</lastModifiedBy>
    <dcterms:modified xsi:type="dcterms:W3CDTF">2020-10-15T04:07:00Z</dcterms:modified>
    <revision>2</revision>
</coreProperties>
```

Microsoft Office validator complains when _xsi:type="dcterms:W3CDTF"_ is missing

**Comment by qmuntal** [comment]
Thanks for reporting this issue @juandemanjon I'll fix it during the following days.

Off-topic: where can I download the Microsoft Office validator you mentioned?

**Comment by juandemanjon** [comment]
Thank you for looking at it.
I have encountered this issue when I was trying to create an Office document with the opc package.
The validator was Microsoft Office itself. Just try to open the generated package with Office.
