### ISSUE TITLE
[Content_Types].xml should not containg an override part of itself

### ISSUE THREAD

**Issue by juandemanjon** [qmuntal/opc#9]
MS Office does not open a document when Content_Types.xml contains an override part of itself

```
    <Override PartName="/[Content_Types].xml" ContentType="text/xml"></Override>
```

**Comment by qmuntal** [comment]
I haven´t seen any rule in the OPC spec saying that `/[Content_Types].xml` cannot appear as override, but as MS Office is a major player I´ll follow this rule and force `/[Content_Types].xml` to appear as default when writing packages.
